# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=50)),
                ('institution', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('requirements', models.CharField(max_length=500)),
                ('links', models.CharField(max_length=100)),
                ('extra', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('documents', models.CharField(max_length=500)),
                ('links', models.CharField(max_length=100)),
            ],
        ),
    ]
