# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
