# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acte', '0002_auto_20170908_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='institution_slug',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='extra',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='links',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='links',
            field=models.CharField(default='', max_length=100),
        ),
    ]
