# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acte', '0002_auto_20170824_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='requirements',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='institution',
            name='documents',
            field=models.CharField(max_length=500),
        ),
    ]
