# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acte', '0003_auto_20170918_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='extra',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='links',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='links',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
